/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.29).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.TaskItem;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.CrossOrigin;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-01-19T22:52:30.362Z[GMT]")
@Validated
public interface TasksApi {

    @Operation(summary = "adds a new task for a user", description = "Adds a task to the todo list", tags={ "tasks" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "task added"),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
        
        @ApiResponse(responseCode = "409", description = "an existing item already exists") })
    @RequestMapping(value = "/tasks",
        consumes = { "application/json" },
        produces = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ApiResponseMessage> addTask(@Parameter(in = ParameterIn.DEFAULT, description = "Inventory item to add", schema=@Schema()) @Valid @RequestBody TaskItem body);


    @Operation(summary = "delete a task", description = "", tags={ "tasks" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "task has been deleted"),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter"),
        
        @ApiResponse(responseCode = "404", description = "task not found") })
    @RequestMapping(value = "/tasks",
    	produces = { "application/json" },
        method = RequestMethod.DELETE)
    @CrossOrigin
    ResponseEntity<ApiResponseMessage> deleteTask(@NotNull @Parameter(in = ParameterIn.QUERY, description = "" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "email", required = true) String email, @NotNull @Parameter(in = ParameterIn.QUERY, description = "" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "taskId", required = true) String taskId);


    @Operation(summary = "edit a task", description = "edit a task from the to do list", tags={ "tasks" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "task added"),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
        
        @ApiResponse(responseCode = "409", description = "an existing item already exists") })
    @RequestMapping(value = "/tasks",
        consumes = { "application/json" },
        produces = { "application/json" },
        method = RequestMethod.PUT)
    @CrossOrigin
    ResponseEntity<ApiResponseMessage> editTask(@NotNull @Parameter(in = ParameterIn.QUERY, description = "" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "email", required = true) String email, @Parameter(in = ParameterIn.DEFAULT, description = "", schema=@Schema()) @Valid @RequestBody TaskItem body);


    @Operation(summary = "", description = "Obtain the list of tasks of a user", tags={ "tasks" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "search results matching criteria", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TaskItem.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/tasks",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<TaskItem>> getTasks(@NotNull @Parameter(in = ParameterIn.QUERY, description = "pass the user Email to get his tasks" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "user", required = true) String user);

}

